"""Optometry knowledge base, part 3: contact lenses + pharmacology + pediatrics/
binocular vision + low vision & instrumentation."""

KB3: list[tuple[str, str, str, str, str]] = [
    # ---------------- contact lenses ----------------
    ("contact", "What is the base curve of a contact lens?",
     "The curvature of its back central optic zone in millimeters or diopters", "back central",
     "The base curve is the radius of the back central optic zone of a lens."),
    ("contact", "What is the most common soft lens base curve?",
     "About 8.4 millimeters", "8.4",
     "Most soft lenses use a base curve near 8.4 millimeters."),
    ("contact", "What does Dk measure in contact lenses?",
     "Oxygen permeability of the material", "permeability",
     "Dk expresses how permeable a lens material is to oxygen."),
    ("contact", "What does Dk/t represent?",
     "Oxygen transmissibility through the lens at its thickness", "transmissibility",
     "Dk over t is oxygen transmissibility through the actual lens."),
    ("contact", "Why is silicone hydrogel good for long wear?",
     "Its silicon channels transmit much more oxygen", "silicon",
     "Silicone hydrogel transmits far more oxygen through silicon channels."),
    ("contact", "What is the HVID used for in fitting?",
     "Choosing the soft lens diameter to cover the cornea with 1 to 2 millimeters of overlap",
     "diameter",
     "Soft lens diameters cover the HVID plus 1 to 2 millimeters."),
    ("contact", "How much soft lens movement is normal on blink?",
     "About 0.5 to 1 millimeter", "0.5 to 1",
     "Soft lenses should move 0.5 to 1 millimeter per blink."),
    ("contact", "What does a tight soft lens fit show?",
     "Reduced movement and a possible lid capture or bulbar conjunctival staining",
     "Reduced movement",
     "Tight fits show reduced movement with staining rings."),
    ("contact", "What does excessive soft lens movement cause?",
     "Fluctuating vision and epithelial staining from edge lift", "edge lift",
     "Loose lenses cause fluctuating vision from edge lift."),
    ("contact", "What is a fluorescein pattern used for in RGP fitting?",
     "Assessing tear layer clearance between lens and cornea", "tear layer",
     "Fluorescein shows the tear layer pool under an RGP lens."),
    ("contact", "What central fluorescein pooling with mid-peripheral touch means in RGP fit?",
     "A steep fit", "steep",
     "Central pooling means the RGP is too steep."),
    ("contact", "What central fluorescein touch with peripheral pooling means in RGP fit?",
     "A flat fit", "flat",
     "Central touch means the RGP is too flat."),
    ("contact", "How does orthokeratology slow myopia progression?",
     "Overnight lens pressure redistributes corneal epithelium to create peripheral myopic defocus",
     "peripheral myopic defocus",
     "Ortho-k reshapes epithelium to create peripheral myopic defocus."),
    ("contact", "Which lens design uses concentric distance and add rings on the back surface?",
     "Multifocal alternating vision rigid lens", "alternating",
     "Alternating design bifocals stack distance and near rings."),
    ("contact", "What is simultaneous vision in multifocal contacts?",
     "Distance and near images superimpose and the brain selects", "superimpose",
     "Simultaneous vision multifocals superimpose distance and near focus."),
    ("contact", "Which lens material is best for keratoconus with severe irregularity?",
     "Scleral lenses", "Scleral",
     "Scleral lenses vault the irregular cornea on a tear reservoir."),
    ("contact", "What is 3 and 9 o'clock staining a sign of?",
     "Poor RGP lens interaction with the limbus in high-riding or low-riding fits",
     "RGP",
     "Three and nine o'clock staining signals limbal interaction with RGP edges."),
    ("contact", "What is a common cause of contact lens related papillary reaction?",
     "Deposits and mechanical irritation causing giant papillary conjunctivitis", "giant papillary",
     "GPC arises from deposits plus mechanical lens irritation."),
    ("contact", "What is the typical replacement schedule for daily disposable lenses?",
     "One day of wear then discard", "One day",
     "Daily disposables are worn once and discarded."),
    ("contact", "Which organisms cause contact lens related Fusarium or Acanthamoeba keratitis risk most with?",
     "Water exposure and poor hygiene", "Water",
     "Water contact and poor hygiene raise Acanthamoeba and Fusarium risk."),
    ("contact", "What emergency symptom pattern suggests microbial keratitis in a wearer?",
     "Painful red eye with photophobia and reduced vision", "Painful",
     "A painful red photophobic eye in a wearer means possible microbial keratitis."),
    ("contact", "Why is overnight wear a risk factor for keratitis?",
     "Hypoxia and epithelial microtrauma accumulate without blinking", "Hypoxia",
     "Overnight hypoxia raises microbial keratitis risk."),
    ("contact", "What prescription property changes with contact lens vertex for powers above 4 diopters?",
     "Effective power must be converted from spectacle plane to corneal plane",
     "vertex",
     "Above 4 diopters, contact power needs vertex conversion."),
    ("contact", "What does a 4 diopter spectacle minus lens become at the corneal plane approximately?",
     "About 3.88 diopters minus", "3.88",
     "A 4 D minus spectacle power is about 3.88 D at the corneal plane."),
    ("contact", "Which myopia control soft lens got FDA approval with dual focus rings?",
     "MiSight", "MiSight",
     "MiSight dual focus lenses are FDA approved for myopia control."),
    ("contact", "What peripheral defocus do myopia control lenses add?",
     "Peripheral myopic defocus to slow axial growth", "Peripheral myopic defocus",
     "Myopia control lenses add peripheral myopic defocus."),
    ("contact", "What does lensawareness in scleral fitting relate to?",
     "Limbal clearance and edge vault", "Limbal",
     "Scleral comfort depends on limbal clearance and edge design."),

    # ---------------- pharmacology ----------------
    ("pharm", "Which mydriatic has the fastest onset and shortest duration?",
     "Tropicamide", "Tropicamide",
     "Tropicamide is the fastest, shortest mydriatic."),
    ("pharm", "How long does typical tropicamide mydriasis last?",
     "About 4 to 6 hours", "4 to 6",
     "Tropicamide dilation lasts about 4 to 6 hours."),
    ("pharm", "Which drug gives strong cycloplegia for uveitis pain?",
     "Atropine or homatropine", "Atropine",
     "Atropine gives long cycloplegia for uveitis comfort."),
    ("pharm", "What is the onset of cyclopentolate 1 percent cycloplegia?",
     "About 30 to 60 minutes", "30 to 60",
     "Cyclopentolate peaks in 30 to 60 minutes."),
    ("pharm", "Which adrenergic agonist dilates without much cycloplegia?",
     "Phenylephrine 2.5 percent", "Phenylephrine",
     "Phenylephrine 2.5 percent dilates with little cycloplegia."),
    ("pharm", "Which glaucoma drop class reduces aqueous production via the ciliary body beta receptors?",
     "Beta blockers such as timolol", "Beta blockers",
     "Timolol lowers IOP by reducing aqueous production."),
    ("pharm", "Which patients must avoid timolol?",
     "Asthmatics, COPD patients, and those with bradycardia or heart block", "Asthmatics",
     "Timolol is contraindicated in asthma and bradycardia."),
    ("pharm", "Which drop class increases uveoscleral outflow?",
     "Prostaglandin analogs", "uveoscleral",
     "Prostaglandin analogs boost uveoscleral outflow."),
    ("pharm", "Which drop class both reduces production and increases outflow through alpha-2 receptors?",
     "Brimonidine", "Brimonidine",
     "Brimonidine acts on alpha-2 receptors for both effects."),
    ("pharm", "Which drop class inhibits carbonic anhydrase topically?",
     "Dorzolamide", "Dorzolamide",
     "Dorzolamide is a topical carbonic anhydrase inhibitor."),
    ("pharm", "Which caution applies to dorzolamide in sulfa allergy?",
     "Cross reactivity is possible", "sulfa",
     "Dorzolamide may cross react in sulfa allergy."),
    ("pharm", "Which direct cholinergic constricts the pupil and contracts the ciliary muscle?",
     "Pilocarpine", "Pilocarpine",
     "Pilocarpine constricts the pupil and ciliary muscle."),
    ("pharm", "Which anesthetic is standard for applanation tonometry?",
     "Proparacaine 0.5 percent", "Proparacaine",
     "Proparacaine 0.5 percent numbs for tonometry."),
    ("pharm", "Why should anesthetic drops never be dispensed for home use?",
     "They blunt healing and can toxicity damage the cornea", "toxicity",
     "Home anesthetic use causes toxic corneal damage."),
    ("pharm", "Which stain glows green under cobalt blue after fluorescein instillation?",
     "Epithelial defects", "Epithelial",
     "Fluorescein highlights epithelial defects under cobalt blue."),
    ("pharm", "Which antiviral gels treat dendritic keratitis?",
     "Ganciclovir 0.15 percent gel", "Ganciclovir",
     "Ganciclovir gel treats epithelial HSV keratitis."),
    ("pharm", "Which oral antibiotic class is typical for preseptal cellulitis?",
     "Amoxicillin-clavulanate", "Amoxicillin",
     "Amoxicillin-clavulanate covers preseptal cellulitis."),
    ("pharm", "Which fluoroquinolone class covers Pseudomonas corneal ulcers?",
     "Fourth generation such as moxifloxacin or besifloxacin", "Fourth generation",
     "Fourth generation fluoroquinolones cover Pseudomonas ulcers."),
    ("pharm", "Which steroid risk escalates with long term use?",
     "Raised IOP, cataract, and infection", "Raised IOP",
     "Long steroids raise IOP, cloud the lens, and risk infection."),
    ("pharm", "Which antihistamine drop class blocks mast cell degranulation plus receptors?",
     "Dual action agents like olopatadine", "olopatadine",
     "Olopatadine stabilizes mast cells and blocks histamine."),
    ("pharm", "What is the first line therapy for allergic conjunctivitis itch?",
     "Topical antihistamine or mast cell stabilizer drops with cold compresses",
     "cold compresses",
     "Allergy itch responds to dual action drops plus cold compresses."),
    ("pharm", "Which systemic drug causes floppy iris during cataract surgery?",
     "Alpha-1 blockers like tamsulosin", "Alpha-1",
     "Alpha-1 blockers predispose to intraoperative floppy iris."),
    ("pharm", "Which glaucoma drop must be refrigerated and causes hyperemia?",
     "Latanoprost", "Latanoprost",
     "Latanoprost is refrigerated and reddens eyes."),
    ("pharm", "What is a preservative in many drops that damages the ocular surface over time?",
     "Benzalkonium chloride", "Benzalkonium",
     "Benzalkonium chloride accumulates and irritates the surface."),

    # ---------------- pediatrics + binocular vision ----------------
    ("peds", "What is a normal refractive state of most newborns?",
     "Mild hyperopia of about 2 to 3 diopters", "hyperopia",
     "Newborns are typically mildly hyperopic by 2 to 3 diopters."),
    ("peds", "Which test detects unequal refractive error in preverbal children?",
     "Retinoscopy or photorefraction", "Retinoscopy",
     "Retinoscopy quantifies error in preverbal children."),
    ("peds", "What is the red reflex test for?",
     "Screening for media opacities and major retinal problems like retinoblastoma",
     "opacities",
     "Red reflex screening catches opacities and retinoblastoma."),
    ("peds", "What is pseudoesotropia?",
     "Epicanthal folds creating the illusion of crossed eyes", "Epicanthal",
     "Pseudoesotropia is the crossed-eye illusion from epicanthal folds."),
    ("peds", "What test distinguishes true strabismus from pseudoesotropia?",
     "The corneal light reflex and cover test", "cover test",
     "Hirschberg reflex plus cover test confirm true strabismus."),
    ("peds", "What does the cover uncover test detect?",
     "A tropia, a manifest deviation", "tropia",
     "Cover-uncover finds manifest tropias."),
    ("peds", "What does the alternate cover test measure?",
     "The total phoria plus tropia deviation", "phoria",
     "Alternate cover reveals total phoria plus tropia."),
    ("peds", "What is a phoria?",
     "A latent deviation that appears only when fusion breaks", "latent",
     "A phoria is latent until fusion breaks."),
    ("peds", "What is a tropia?",
     "A constant manifest eye deviation", "manifest",
     "A tropia is a constant manifest deviation."),
    ("peds", "What is amblyopia?",
     "Reduced best corrected acuity without structural cause, from abnormal visual development",
     "development",
     "Amblyopia is reduced best corrected acuity from abnormal development."),
    ("peds", "Which amblyopia type comes from uncorrected anisometropia?",
     "Refractive amblyopia", "Refractive",
     "Anisometropia causes refractive amblyopia."),
    ("peds", "What is the first treatment step in refractive amblyopia?",
     "Prescribing the full cycloplegic correction", "correction",
     "Full correction alone often improves refractive amblyopia."),
    ("peds", "What is the standard patching dose range for moderate amblyopia?",
     "2 to 6 hours daily", "2 to 6",
     "Moderate amblyopia patches 2 to 6 hours daily."),
    ("peds", "What alternative to patching treats amblyopia with drops?",
     "Atropine penalization", "Atropine",
     "Atropine drops penalize the sound eye."),
    ("peds", "Until about what age can amblyopia still respond to therapy?",
     "Around 12 years, with best response before 8", "before 8",
     "Amblyopia responds best before age 8 with benefit to 12."),
    ("peds", "Which chart uses Lea symbols or HOTV for preschoolers?",
     "Optotype acuity charts for pre-readers", "HOTV",
     "HOTV and LEA symbols test preschool acuity."),
    ("peds", "What is the preferential looking test used in infancy?",
     "Teller acuity cards with graded grating stripes", "Teller",
     "Teller cards measure infant acuity by preferential looking."),
    ("peds", "What is strabismic amblyopia caused by?",
     "Chronic suppression of a deviating eye", "suppression",
     "Constant suppression of a turned eye causes strabismic amblyopia."),
    ("peds", "What is congenital esotropia timing?",
     "Onset before 6 months of age", "before 6 months",
     "Infantile esotropia starts before 6 months."),
    ("peds", "What treatable cause of acquired esotropia in children 2 to 5 is hyperopia?",
     "Accommodative esotropia", "Accommodative",
     "Accommodative esotropia resolves with hyperopic correction."),
    ("peds", "What add helps accommodative esotropia at near?",
     "A bifocal add of about +2.50", "+2.50",
     "A +2.50 add controls near accommodative esotropia."),
    ("peds", "Which syndrome has narrowed palpebral fissures, ptosis, and epicanthus?",
     "Blepharophimosis syndrome", "Blepharophimosis",
     "Blepharophimosis gives small lids with ptosis."),
    ("peds", "Which vision development milestone should be mature by about age 6?",
     "Monocular acuity of 20/20 with stereoacuity", "20/20",
     "Adult level acuity and stereo mature near age 6."),
    ("peds", "What is stereoacuity?",
     "The smallest horizontal disparity giving binocular depth", "disparity",
     "Stereoacuity is the finest binocular depth disparity seen."),
    ("peds", "What is the best stereoacuity a normal adult achieves on Titmus circles?",
     "About 40 seconds of arc", "40",
     "Titmus stereoacuity bottoms out near 40 arc seconds."),
    ("peds", "What does suppression in strabismus prevent?",
     "Diplopia at the cost of binocular cooperation", "Diplopia",
     "Suppression avoids double vision but blocks binocularity."),
    ("peds", "Which test uses polarized glasses and random dot stereograms?",
     "Randot stereotest", "Randot",
     "Randot testing uses random dot polarized targets."),
    ("peds", "What is convergence insufficiency?",
     "Near exophoria with reduced positive fusional vergence and low NPC",
     "reduced positive fusional vergence",
     "CI shows near exophoria with low PFV and receded NPC."),
    ("peds", "What is the evidence based therapy for convergence insufficiency?",
     "Office based vergence therapy with home reinforcement", "Office based",
     "Office vergence therapy is the proven CI treatment."),
    ("peds", "Which school age symptom cluster suggests CI?",
     "Headaches, blurred or doubled text after reading", "doubled",
     "CI causes end of day reading blur and diplopia."),
    ("peds", "What is a normal near point of convergence break?",
     "About 6 to 10 centimeters", "6 to 10",
     "NPC normally breaks near 6 to 10 centimeters."),
    ("peds", "What is fusional vergence facility?",
     "The rate of vergence adaptation with prisms per minute, about 15 cycles per minute normal",
     "15",
     "Vergence facility flips base-in base-out near 15 cycles per minute."),
    ("peds", "What does NRA measure?",
     "Relative plus tolerance at near, about +2.50 normally", "+2.50",
     "NRA is about +2.50 of relative plus at near."),
    ("peds", "What does PRA measure?",
     "Relative minus tolerance at near, about -2.25 normally", "-2.25",
     "PRA is about -2.25 of relative minus at near."),
    ("peds", "Which law states equal innervation flows to yoked muscles of both eyes?",
     "Hering's law", "Hering",
     "Hering's law sends equal innervation to yoke muscles."),
    ("peds", "Which law states increased innervation to an agonist decreases its antagonist?",
     "Sherrington's law", "Sherrington",
     "Sherrington's law pairs agonist inhibition with antagonist relaxation."),
    ("peds", "What is DVD in strabismus terms?",
     "Dissociated vertical deviation, an upward drift of the covered eye", "Dissociated vertical",
     "DVD is an upward drift when an eye is covered."),
    ("peds", "What is Brown syndrome?",
     "Restricted elevation in adduction from superior oblique tendon tightness",
     "superior oblique tendon",
     "Brown syndrome restricts adducted elevation via SO tendon."),
    ("peds", "What is Duane syndrome?",
     "A congenital abduction or adduction deficit with globe retraction", "retraction",
     "Duane syndrome retracts the globe on attempted adduction."),

    # ---------------- low vision + instruments + systemic ----------------
    ("lowvision", "What US acuity defines legal blindness?",
     "20/200 or worse in the better eye, or a field of 20 degrees or less", "20/200",
     "Legal blindness is 20/200 or worse or 20 degree fields."),
    ("lowvision", "What magnification does a 16 diopter handheld loupe give?",
     "4x, since magnification equals diopters divided by 4", "4x",
     "A 16 D loupe magnifies 4 times, diopters over four."),
    ("lowvision", "What is the Kestenbaum rule for adding plus?",
     "The denominator of best acuity divided by 100 gives the add power", "denominator",
     "Kestenbaum's rule sets add as the acuity denominator over 100."),
    ("lowvision", "What device projects magnified text onto a screen for low vision reading?",
     "A CCTV video magnifier", "CCTV",
     "Desktop CCTV magnifiers enlarge print on a screen."),
    ("lowvision", "Which low vision aid helps mid-peripheral field loss like RP?",
     "Prisms or reverse telescopes for field expansion", "field expansion",
     "Field expanders compensate tubular RP fields."),
    ("lowvision", "What lighting strategy helps most low vision readers?",
     "Bright, angled task lighting without glare", "task lighting",
     "Angled glare-free task light aids low vision reading."),
    ("lowvision", "Which contrast trick helps low vision kitchens?",
     "High contrast markings on knobs and edges", "High contrast",
     "High contrast marking aids daily tasks."),
    ("lowvision", "What does a telescopic loupe trade for magnification?",
     "Reduced field of view and working distance", "field of view",
     "Telescopes magnify at the cost of field."),
    ("instruments", "What does Goldmann applanation tonometry measure?",
     "The force to flatten a fixed 3.06 millimeter corneal area", "3.06",
     "Goldmann flattens a 3.06 millimeter zone to estimate IOP."),
    ("instruments", "Why is 3.06 millimeters the Goldmann diameter?",
     "Corneal rigidity and tear film capillary forces cancel out", "rigidity",
     "At 3.06 millimeters, rigidity and tear forces balance."),
    ("instruments", "What can falsely lower Goldmann readings?",
     "Thin central corneas", "Thin",
     "Thin corneas make Goldmann underestimate IOP."),
    ("instruments", "What can falsely raise Goldmann readings?",
     "Thick corneas or a tight collar and breath holding", "Thick",
     "Thick corneas and Valsalva inflate Goldmann IOP."),
    ("instruments", "How does iCare rebound tonometry work?",
     "A light probe bounces off the cornea and deceleration is converted to IOP",
     "probe",
     "Rebound tonometry reads IOP from probe deceleration."),
    ("instruments", "What does van Herick grading estimate?",
     "Angle depth from peripheral anterior chamber to corneal thickness ratio",
     "Angle depth",
     "Van Herick compares peripheral chamber depth to corneal thickness."),
    ("instruments", "Which van Herick grade suggests angle closure risk?",
     "Grade 2 or less, chamber less than one quarter thickness", "Grade 2",
     "Van Herick grade 2 or less flags closure risk."),
    ("instruments", "What does gonioscopy directly visualize?",
     "The anterior chamber angle structures", "angle",
     "Gonioscopy shows angle structures directly."),
    ("instruments", "What do the slit lamp illumination techniques include?",
     "Diffuse, direct focal, indirect, retroillumination, specular, and sclerotic scatter",
     "retroillumination",
     "Slit lamp methods span diffuse to sclerotic scatter."),
    ("instruments", "What does OCT measure in the macula?",
     "Cross sectional retinal thickness and layer anatomy", "thickness",
     "OCT maps macular layer thickness."),
    ("instruments", "What is fundus autofluorescence used for?",
     "Mapping RPE lipofuscin changes in macular disease", "lipofuscin",
     "FAF maps lipofuscin patterns of RPE health."),
    ("instruments", "What does a lensometer measure?",
     "Spectacle power, prism, and add through focusing", "Spectacle power",
     "A lensometer reads spectacle power and prism."),
    ("instruments", "What does autorefraction provide?",
     "An objective starting point for subjective refraction", "objective",
     "Autorefractors give an objective refractive starting point."),
    ("systemic", "Which cranial nerve palsy causes vertical diplopia worse in downgaze to the opposite side?",
     "Superior oblique palsy, or fourth nerve palsy", "fourth nerve",
     "Fourth nerve palsy worsens contralateral downgaze diplopia."),
    ("systemic", "Which nerve palsy turns the eye down and out with ptosis and blown pupil?",
     "Third nerve palsy with pupil involvement", "Third nerve",
     "A pupillary third nerve palsy is an emergency workup."),
    ("systemic", "Which cause of isolated sixth nerve palsy in adults needs neuroimaging when painful?",
     "Inflammation or mass until proven otherwise", "neuroimaging",
     "Painful sixth palsy warrants imaging."),
    ("systemic", "Which systemic sign pairs with juvenile xanthogranuloma iris lesions?",
     "Orange skin papules", "papules",
     "JXG pairs iris lesions with orange papules."),
    ("systemic", "Which finding on the iris suggests neurofibromatosis type 1?",
     "Lisch nodules", "Lisch",
     "Lisch nodules are iris hamartomas of NF1."),
    ("systemic", "Which lens change is classic in Down syndrome?",
     "Cerulean cataract specks", "Cerulean",
     "Down syndrome shows cerulean lens dots."),
    ("systemic", "Which corneal ring suggests Wilson disease on exam?",
     "Kayser-Fleischer ring", "Kayser-Fleischer",
     "Wilson disease rings the cornea with copper."),
    ("systemic", "Which anemia causes conjunctival pallor check first?",
     "Any anemia, best seen in the palpebral conjunctiva", "palpebral",
     "Palpebral conjunctiva pallor screens anemia."),
    ("systemic", "Which sickle cell retinal sign is peripheral salmon patch hemorrhage?",
     "Peripheral retinal arteriolar occlusion", "salmon patch",
     "Sickle retinopathy shows salmon patch hemorrhages."),
    ("systemic", "Which connective tissue disease associates with keratoconus eye rubbing and atopy?",
     "Down syndrome and atopic disease", "atopy",
     "Atopy and Down syndrome raise keratoconus risk."),
    ("systemic", "Which vitamin deficiency causes corneal xerosis with Bitot spots?",
     "Vitamin A", "Vitamin A",
     "Bitot spots mark vitamin A deficiency."),
    ("systemic", "Which hypertension target organ sign appears in the retina?",
     "Arteriolar narrowing and AV nicking", "Arteriolar",
     "Retinal arteriolar change signals hypertensive damage."),
    ("systemic", "What blood sugar range is the ADA recommended HbA1c goal generally?",
     "Below 7 percent for most adults", "7",
     "Most adults aim for HbA1c under 7 percent."),
    ("systemic", "Which medication class for type 2 diabetes reduced diabetic retinopathy progression in trials?",
     "Semaglutide has mixed data; fenofibrate showed benefit", "fenofibrate",
     "Fenofibrate reduced DR progression in major trials."),
]
