"""Optometry knowledge base, part 1: ocular anatomy + physiological optics.

Entry format: (domain, question, answer, key, statement)
  key       - short canonical answer token(s) that appear inside `statement`
              (used by the forge for cloze + true/false synthesis)
  statement - declarative sentence for LM training (grammar quality matters)
"""

KB1: list[tuple[str, str, str, str, str]] = [
    # ---------------- ocular anatomy ----------------
    ("anatomy", "How many layers does the cornea have?",
     "Five: the epithelium, Bowman's layer, the stroma, Descemet's membrane, and the endothelium",
     "five",
     "The cornea has five layers: the epithelium, Bowman's layer, the stroma, Descemet's membrane, and the endothelium."),
    ("anatomy", "What is the average central corneal thickness?",
     "About 540 micrometers", "540",
     "The average central corneal thickness is about 540 micrometers."),
    ("anatomy", "Which corneal layer is the thinnest?",
     "Descemet's membrane", "Descemet's membrane",
     "Descemet's membrane is the thinnest layer of the cornea."),
    ("anatomy", "Which corneal layer makes up about 90 percent of the corneal thickness?",
     "The stroma", "stroma",
     "The stroma makes up about 90 percent of the corneal thickness."),
    ("anatomy", "How many endothelial cells per square millimeter do young adults have?",
     "About 3,500", "3,500",
     "Young adults have about 3,500 corneal endothelial cells per square millimeter."),
    ("anatomy", "Can the corneal endothelium regenerate?",
     "No, endothelial cells do not divide; neighboring cells migrate and enlarge to cover gaps",
     "do not divide",
     "Corneal endothelial cells do not divide, so cell loss is permanent."),
    ("anatomy", "What provides most of the eye's refractive power?",
     "The cornea, contributing about 43 diopters", "43",
     "The cornea provides about 43 diopters, roughly two thirds of the eye's refractive power."),
    ("anatomy", "Why is the cornea transparent?",
     "Its regular collagen lattice and relative dehydration keep it clear",
     "regular collagen lattice",
     "The cornea stays transparent because of its regular collagen lattice and relative dehydration."),
    ("anatomy", "Is the cornea vascularized?",
     "No, it is avascular and is nourished by aqueous humor, tears, and limbal vessels",
     "avascular",
     "The cornea is avascular and is nourished by aqueous humor and tears."),
    ("anatomy", "Which nerve provides sensory innervation to the cornea?",
     "The ophthalmic division of the trigeminal nerve (CN V1)", "trigeminal",
     "The cornea receives sensory innervation from the ophthalmic division of the trigeminal nerve."),
    ("anatomy", "What covers the posterior five sixths of the eyeball?",
     "The sclera", "sclera",
     "The sclera covers the posterior five sixths of the eyeball."),
    ("anatomy", "What is the limbus?",
     "The junction between the cornea and the sclera", "junction",
     "The limbus is the junction between the cornea and the sclera."),
    ("anatomy", "Which angle structures are found at the limbus?",
     "The trabecular meshwork and the canal of Schlemm", "trabecular meshwork",
     "The trabecular meshwork and the canal of Schlemm sit at the limbus."),
    ("anatomy", "What drains aqueous humor from the anterior chamber?",
     "The trabecular meshwork into the canal of Schlemm", "canal of Schlemm",
     "Aqueous humor drains through the trabecular meshwork into the canal of Schlemm."),
    ("anatomy", "Which structure produces aqueous humor?",
     "The ciliary body epithelium", "ciliary body",
     "The ciliary body epithelium produces aqueous humor."),
    ("anatomy", "What is the volume of the anterior chamber?",
     "About 250 microliters", "250",
     "The anterior chamber holds about 250 microliters of aqueous humor."),
    ("anatomy", "Where is the posterior chamber?",
     "Between the posterior iris surface and the lens zonules", "zonules",
     "The posterior chamber lies between the posterior iris surface and the lens zonules."),
    ("anatomy", "What is the volume of the vitreous chamber?",
     "About 4 milliliters", "4",
     "The vitreous chamber holds about 4 milliliters of vitreous."),
    ("anatomy", "How many layers does the retina have?",
     "Ten", "Ten",
     "The retina has ten layers."),
    ("anatomy", "What is the macula?",
     "The 5.5 millimeter area at the posterior pole responsible for central vision", "5.5",
     "The macula is a 5.5 millimeter area at the posterior pole for central vision."),
    ("anatomy", "What is the fovea?",
     "The central pit of the macula with the highest cone density and sharpest acuity", "cone density",
     "The fovea is the central pit of the macula with the highest cone density."),
    ("anatomy", "Which retinal area is completely free of blood vessels?",
     "The foveal avascular zone", "avascular",
     "The foveal avascular zone at the fovea center is free of blood vessels."),
    ("anatomy", "How many rods are in a human retina?",
     "About 120 million", "120 million",
     "The human retina contains about 120 million rods."),
    ("anatomy", "How many cones are in a human retina?",
     "About 6 million", "6 million",
     "The human retina contains about 6 million cones."),
    ("anatomy", "Which photoreceptors mediate night vision?",
     "Rods", "Rods",
     "Rods mediate scotopic, or night, vision."),
    ("anatomy", "Which photoreceptors mediate color vision?",
     "Cones", "Cones",
     "Cones mediate photopic and color vision."),
    ("anatomy", "Where is cone density highest?",
     "At the fovea", "fovea",
     "Cone density peaks at the fovea."),
    ("anatomy", "Why is the optic disc called the blind spot?",
     "It has no photoreceptors where ganglion axons exit the eye", "no photoreceptors",
     "The optic disc is the blind spot because it has no photoreceptors."),
    ("anatomy", "What is the normal cup to disc ratio?",
     "About 0.3", "0.3",
     "The normal cup to disc ratio is about 0.3."),
    ("anatomy", "Which cranial nerve is the optic nerve?",
     "Cranial nerve II", "II",
     "The optic nerve is cranial nerve II."),
    ("anatomy", "How many axons does the human optic nerve carry?",
     "About 1.2 million", "1.2 million",
     "The optic nerve carries about 1.2 million retinal ganglion cell axons."),
    ("anatomy", "Which layer supplies the outer retina?",
     "The choriocapillaris of the choroid", "choroid",
     "The choroid supplies the outer retina."),
    ("anatomy", "From which artery does the central retinal artery arise?",
     "The ophthalmic artery", "ophthalmic artery",
     "The central retinal artery arises from the ophthalmic artery."),
    ("anatomy", "How many extraocular muscles move each eye?",
     "Six", "Six",
     "Six extraocular muscles move each eye."),
    ("anatomy", "Which cranial nerve innervates the lateral rectus?",
     "The abducens nerve (CN VI)", "abducens",
     "The abducens nerve, CN VI, innervates the lateral rectus."),
    ("anatomy", "Which cranial nerve innervates the superior oblique?",
     "The trochlear nerve (CN IV)", "trochlear",
     "The trochlear nerve, CN IV, innervates the superior oblique."),
    ("anatomy", "Which muscles does the oculomotor nerve innervate?",
     "The medial rectus, superior rectus, inferior rectus, inferior oblique, and levator",
     "medial rectus",
     "The oculomotor nerve innervates the medial rectus, superior rectus, inferior rectus, inferior oblique, and levator."),
    ("anatomy", "What is the primary action of the lateral rectus?",
     "Abduction", "Abduction",
     "The primary action of the lateral rectus is abduction."),
    ("anatomy", "What is the primary action of the medial rectus?",
     "Adduction", "Adduction",
     "The primary action of the medial rectus is adduction."),
    ("anatomy", "What is the primary action of the superior rectus?",
     "Elevation", "Elevation",
     "The primary action of the superior rectus is elevation."),
    ("anatomy", "What is the primary action of the inferior rectus?",
     "Depression", "Depression",
     "The primary action of the inferior rectus is depression."),
    ("anatomy", "What is the primary action of the superior oblique?",
     "Intorsion, strongest when the eye is adducted", "Intorsion",
     "The primary action of the superior oblique is intorsion."),
    ("anatomy", "What is the primary action of the inferior oblique?",
     "Extorsion, strongest when the eye is adducted", "Extorsion",
     "The primary action of the inferior oblique is extorsion."),
    ("anatomy", "Which muscle raises the upper eyelid?",
     "The levator palpebrae superioris", "levator",
     "The levator palpebrae superioris raises the upper eyelid."),
    ("anatomy", "Which smooth muscle assists upper lid elevation?",
     "The superior tarsal muscle, or Muller's muscle", "Muller",
     "Muller's muscle, the superior tarsal muscle, assists upper lid elevation."),
    ("anatomy", "Which muscle closes the eyelids?",
     "The orbicularis oculi", "orbicularis oculi",
     "The orbicularis oculi closes the eyelids."),
    ("anatomy", "Which nerve innervates the orbicularis oculi?",
     "The facial nerve (CN VII)", "facial",
     "The facial nerve, CN VII, innervates the orbicularis oculi."),
    ("anatomy", "What are the three layers of the tear film?",
     "Lipid, aqueous, and mucin", "Lipid",
     "The tear film has three layers: lipid, aqueous, and mucin."),
    ("anatomy", "Which glands secrete the lipid layer of tears?",
     "The meibomian glands", "meibomian",
     "The meibomian glands secrete the lipid layer of the tear film."),
    ("anatomy", "Which cells secrete the mucin layer of tears?",
     "Conjunctival goblet cells", "goblet",
     "Conjunctival goblet cells secrete the mucin layer of the tear film."),
    ("anatomy", "Where is the main lacrimal gland located?",
     "In the superotemporal orbit", "superotemporal",
     "The main lacrimal gland sits in the superotemporal orbit."),
    ("anatomy", "Through which structure do tears drain into the nose?",
     "The nasolacrimal duct into the inferior meatus", "nasolacrimal duct",
     "Tears drain through the nasolacrimal duct into the inferior meatus."),
    ("anatomy", "What is the normal blink rate?",
     "About 15 to 20 blinks per minute", "15 to 20",
     "The normal blink rate is about 15 to 20 blinks per minute."),
    ("anatomy", "Which iris muscle constricts the pupil?",
     "The iris sphincter muscle", "sphincter",
     "The iris sphincter muscle constricts the pupil."),
    ("anatomy", "Which iris muscle dilates the pupil?",
     "The iris dilator muscle", "dilator",
     "The iris dilator muscle dilates the pupil."),
    ("anatomy", "Which nervous system controls the iris sphincter?",
     "The parasympathetic system via CN III", "parasympathetic",
     "Parasympathetic fibers via CN III control the iris sphincter."),
    ("anatomy", "What is the typical pupil diameter?",
     "Between 2 and 8 millimeters depending on lighting", "2 and 8",
     "The pupil ranges between 2 and 8 millimeters depending on lighting."),
    ("anatomy", "How much anisocoria is considered physiologic?",
     "Up to 1 millimeter", "1 millimeter",
     "Anisocoria up to 1 millimeter can be physiologic."),
    ("anatomy", "What shape is the crystalline lens?",
     "Biconvex and transparent", "Biconvex",
     "The crystalline lens is biconvex and transparent."),
    ("anatomy", "Does the lens grow throughout life?",
     "Yes, new lens fibers are added for life", "grows",
     "The lens grows throughout life as new fibers are added."),
    ("anatomy", "What holds the lens in place?",
     "The zonular fibers of Zinn", "zonular",
     "The zonular fibers of Zinn hold the lens in place."),
    ("anatomy", "What happens to the lens during accommodation?",
     "The ciliary muscle contracts, the zonules slacken, and the lens rounds up",
     "rounds",
     "During accommodation the ciliary muscle contracts, the zonules slacken, and the lens rounds up."),
    ("anatomy", "What is presbyopia?",
     "Age related loss of accommodation, usually noticed in the early forties", "forties",
     "Presbyopia is age related loss of accommodation noticed in the early forties."),
    ("anatomy", "What does the retinal pigment epithelium do?",
     "Nourishes photoreceptors and phagocytoses their outer segments", "phagocytoses",
     "The retinal pigment epithelium phagocytoses shed photoreceptor outer segments."),
    ("anatomy", "Which retinal visual pigment do rods contain?",
     "Rhodopsin", "Rhodopsin",
     "Rods contain the visual pigment rhodopsin."),
    ("anatomy", "Do nasal retinal fibers cross at the chiasm?",
     "Yes, nasal fibers cross and temporal fibers stay ipsilateral", "cross",
     "Nasal retinal fibers cross at the chiasm while temporal fibers stay ipsilateral."),
    ("anatomy", "Where does the optic tract terminate?",
     "The lateral geniculate nucleus", "lateral geniculate",
     "The optic tract terminates in the lateral geniculate nucleus."),
    ("anatomy", "Which visual cortex area receives primary input?",
     "V1 along the calcarine fissure", "calcarine",
     "Primary visual input reaches V1 along the calcarine fissure."),
    ("anatomy", "Which structure is damaged in a superior visual field defect from temporal lobe lesions?",
     "Meyer's loop of the optic radiations", "Meyer's loop",
     "Meyer's loop in the temporal lobe carries inferior field fibers, so lesions lift the visual field."),
    ("anatomy", "What is the afferent limb of the pupillary light reflex?",
     "The optic nerve (CN II)", "optic nerve",
     "The afferent limb of the light reflex is the optic nerve."),
    ("anatomy", "What is the efferent limb of the pupillary light reflex?",
     "CN III to the iris sphincter", "CN III",
     "The efferent limb of the light reflex travels on CN III."),
    ("anatomy", "What is the corneal reflex pathway?",
     "Afferent CN V1, efferent CN VII", "CN V1",
     "The corneal reflex has an afferent CN V1 limb and an efferent CN VII limb."),
    ("anatomy", "What is Bell's phenomenon?",
     "Eyes rotate up and out during forced eyelid closure", "rotate up",
     "Bell's phenomenon is the upward rotation of the eyes during forced closure."),
    ("anatomy", "How many meibomian glands are in the upper lid?",
     "About 25", "25",
     "The upper lid has about 25 meibomian glands."),
    ("anatomy", "What is the average adult axial length of the eye?",
     "About 23.5 to 24 millimeters", "23.5",
     "The average adult axial length is about 23.5 to 24 millimeters."),
    ("anatomy", "How much myopia does one millimeter of axial elongation cause?",
     "About 2.5 to 3 diopters", "2.5",
     "Each millimeter of axial elongation adds about 2.5 to 3 diopters of myopia."),
    ("anatomy", "What is the volume of the adult globe?",
     "About 6.5 milliliters", "6.5",
     "The adult globe has a volume of about 6.5 milliliters."),
    ("anatomy", "Which conjunctiva lines the eyelids?",
     "The palpebral conjunctiva", "palpebral",
     "The palpebral conjunctiva lines the eyelids."),

    # ---------------- physiological optics ----------------
    ("optics", "What is Prentice's rule?",
     "Prism diopters equal decentration in centimeters times lens power", "Prentice",
     "Prentice's rule states that induced prism equals decentration in centimeters times lens power."),
    ("optics", "How do you transpose a prescription from plus cylinder to minus cylinder?",
     "Add the cylinder to the sphere, flip the cylinder sign, and rotate the axis 90 degrees",
     "rotate the axis",
     "To transpose a prescription you add the cylinder to the sphere, flip the cylinder sign, and rotate the axis 90 degrees."),
    ("optics", "What is the spherical equivalent of a prescription?",
     "Sphere plus half the cylinder", "half",
     "The spherical equivalent equals the sphere plus half the cylinder."),
    ("optics", "How does lens power change with vertex distance?",
     "Effective power equals lens power divided by one minus distance in meters times power",
     "Effective power",
     "Effective power equals the lens power divided by one minus the vertex distance in meters times the power."),
    ("optics", "What is the average spectacle vertex distance?",
     "About 12 millimeters", "12",
     "The average spectacle vertex distance is about 12 millimeters."),
    ("optics", "What is one prism diopter?",
     "A deviation of 1 centimeter at 1 meter, about 0.57 degrees", "0.57",
     "One prism diopter deviates light 1 centimeter at 1 meter, about 0.57 degrees."),
    ("optics", "How much accommodation is needed to read at 40 centimeters?",
     "2.50 diopters", "2.50",
     "Reading at 40 centimeters requires 2.50 diopters of accommodation."),
    ("optics", "What is a normal AC/A ratio?",
     "About 3 prism diopters per diopter of accommodation", "3",
     "A normal AC/A ratio is about 3 prism diopters per diopter of accommodation."),
    ("optics", "In duochrome testing, what does the red side looking clearer mean?",
     "The eye is under-minused, or myopically overcorrected", "under-minused",
     "A clearer red duochrome target means the eye is under-minused."),
    ("optics", "In duochrome testing, what does the green side looking clearer mean?",
     "The eye is over-minused, or hyperopically undercorrected", "over-minused",
     "A clearer green duochrome target means the eye is over-minused."),
    ("optics", "What does 20/20 mean in visual angle terms?",
     "The whole letter subtends 5 minutes of arc and each stroke 1 minute", "5 minutes",
     "A 20/20 letter subtends 5 minutes of arc with 1 minute strokes."),
    ("optics", "What logMAR value corresponds to 20/20?",
     "0.0", "0.0",
     "A logMAR acuity of 0.0 equals 20/20."),
    ("optics", "How much does each ETDRS letter change logMAR?",
     "0.02 log units", "0.02",
     "Each ETDRS letter is worth 0.02 logMAR."),
    ("optics", "What is the MAR of 20/40 acuity?",
     "2 minutes of arc, logMAR 0.30", "0.30",
     "The minimum angle of resolution at 20/40 is 2 minutes, logMAR 0.30."),
    ("optics", "Why does a pinhole improve refractive blur?",
     "It narrows the light bundle and increases depth of focus", "depth of focus",
     "A pinhole improves blur by increasing depth of focus."),
    ("optics", "What does it mean when a pinhole does not improve vision?",
     "Reduced acuity is likely from pathology rather than refractive error", "pathology",
     "Vision that a pinhole cannot improve suggests pathology rather than refractive error."),
    ("optics", "What is the circle of least diffusion?",
     "The clearest focus point of the Sturm conoid in astigmatism", "Sturm",
     "The circle of least diffusion sits between the two focal lines of the Sturm conoid."),
    ("optics", "What motion on retinoscopy means the eye is over-minused?",
     "With motion", "With motion",
     "With motion on retinoscopy means you should add plus power."),
    ("optics", "What motion on retinoscopy means you should add minus power?",
     "Against motion", "Against",
     "Against motion on retinoscopy means you should add minus power."),
    ("optics", "What working distance lens is used at 50 centimeters retinoscopy?",
     "+2.00 diopters", "2.00",
     "A +2.00 diopter working distance lens compensates at 50 centimeters."),
    ("optics", "What working distance lens is used at 67 centimeters retinoscopy?",
     "+1.50 diopters", "1.50",
     "A +1.50 diopter working distance lens compensates at 67 centimeters."),
    ("optics", "What is the purpose of fogging in refraction?",
     "Relax accommodation by deliberately over-plussing", "over-plussing",
     "Fogging relaxes accommodation by deliberately over-plussing the eye."),
    ("optics", "Which axis range is with-the-rule astigmatism in minus cylinder form?",
     "Axis 180 plus or minus 15 degrees", "180",
     "With-the-rule astigmatism has its minus cylinder axis near 180 degrees."),
    ("optics", "Which axis range is against-the-rule astigmatism in minus cylinder form?",
     "Axis 90 plus or minus 15 degrees", "90",
     "Against-the-rule astigmatism has its minus cylinder axis near 90 degrees."),
    ("optics", "How does the clock dial chart locate cylinder axis?",
     "Multiply the faintest clock hour by 30 degrees", "30",
     "On a clock dial chart the faintest hour times 30 degrees gives the axis."),
    ("optics", "What does the Jackson cross cylinder test first?",
     "Cylinder axis, then cylinder power", "axis",
     "The Jackson cross cylinder refines cylinder axis first and then power."),
    ("optics", "In JCC axis refinement, which way do you rotate the axis when the red line clears?",
     "Toward the red dots on the JCC", "red",
     "You chase the red dots when refining axis with the JCC."),
    ("optics", "What is an Abbe number?",
     "A measure of optical dispersion; higher means less chromatic aberration", "dispersion",
     "The Abbe number measures dispersion, and higher values mean less chromatic aberration."),
    ("optics", "What is the Abbe value of CR-39?",
     "About 58", "58",
     "CR-39 has an Abbe value of about 58."),
    ("optics", "What is the Abbe value of polycarbonate?",
     "About 30", "30",
     "Polycarbonate has an Abbe value of about 30."),
    ("optics", "What is the refractive index of CR-39?",
     "1.498", "1.498",
     "CR-39 has a refractive index of 1.498."),
    ("optics", "What is the highest common spectacle lens index?",
     "1.74", "1.74",
     "The highest common lens index is 1.74."),
    ("optics", "Why do prisms displace images without changing size?",
     "Prisms deviate light toward their base so the image shifts toward the apex",
     "apex",
     "A prism deviates light toward its base and the seen image shifts toward its apex."),
    ("optics", "Which direction is a compensating prism placed to correct a right hyperphoria?",
     "Base down before the right eye or base up before the left", "Base down",
     "A right hyperphoria is compensated base down before the right eye or base up before the left."),
    ("optics", "What is slab-off grinding used for?",
     "Adding base-up prism to the more minus lens to cancel vertical imbalance at near",
     "vertical imbalance",
     "Slab-off grinding adds base-up prism to the more minus lens to fix vertical imbalance."),
    ("optics", "What is prism thinning in progressive lenses?",
     "Base-down prism added to both lower lens halves to thin the lenses", "Base-down",
     "Prism thinning adds base-down prism to slim progressive lenses."),
    ("optics", "What is the average pantoscopic tilt of spectacles?",
     "8 to 12 degrees", "8 to 12",
     "Spectacles are fitted with about 8 to 12 degrees of pantoscopic tilt."),
    ("optics", "What is decentration per lens?",
     "Half the frame PD minus the monocular PD", "half",
     "Decentration per lens equals half the frame PD minus the monocular PD."),
    ("optics", "How much prism does 4 millimeters of decentration induce on a 5 diopter lens?",
     "2 prism diopters", "2",
     "Four millimeters of decentration on a 5 diopter lens induces 2 prism diopters by Prentice's rule."),
    ("optics", "What is spectacle magnification?",
     "The retinal image size change from power factor times shape factor", "power factor",
     "Spectacle magnification is the product of the power factor and the shape factor."),
    ("optics", "At what image size difference does aniseikonia usually become symptomatic?",
     "Around 3 percent", "3 percent",
     "Aniseikonia usually becomes symptomatic near a 3 percent image size difference."),
    ("optics", "How do contact lenses change retinal image size for myopes compared with spectacles?",
     "They give myopes a larger retinal image than spectacles", "larger",
     "Contact lenses give myopes a larger retinal image than spectacles do."),
    ("optics", "What is jack-in-the-box effect?",
     "Ring scotoma of high plus or minus lenses making objects pop in and out of view",
     "Ring scotoma",
     "High powered lenses create a ring scotoma that causes the jack-in-the-box effect."),
    ("optics", "What is the base curve rule of thumb for plus lenses, Vogel's rule?",
     "Base curve equals the spherical equivalent plus 6 diopters", "plus 6",
     "Vogel's rule for plus lenses sets the base curve at the spherical equivalent plus 6 diopters."),
    ("optics", "What does the add power of a presbyopic lens represent?",
     "The extra plus power needed at near beyond distance correction", "extra plus",
     "The add is the extra plus power a presbyope needs at near."),
    ("optics", "What is a rough rule for choosing a reading add?",
     "Working distance demand minus half the remaining accommodative amplitude",
     "half",
     "A practical add is the dioptric working distance minus half the accommodative amplitude."),
    ("optics", "Why does a Fresnel membrane prism reduce lens weight?",
     "It is a thin press-on sheet instead of ground-in prism mass", "thin",
     "Fresnel prisms are thin press-on sheets that avoid grinding prism into the lens."),
    ("optics", "What do polarized sunglass lenses remove?",
     "Horizontally polarized glare from surfaces like water and roads", "Horizontally",
     "Polarized lenses block horizontally polarized glare such as water reflections."),
    ("optics", "Which tint is commonly used for migraine and blepharospasm light sensitivity?",
     "FL-41", "FL-41",
     "The FL-41 rose tint helps migraine and blepharospasm photophobia."),
    ("optics", "What is contrast sensitivity testing used for?",
     "Detecting vision loss when high contrast acuity is still normal", "Contrast",
     "Contrast sensitivity can reveal loss when standard acuity looks normal."),
    ("optics", "What is a normal Pelli-Robson contrast sensitivity score?",
     "About 1.65 log units or better", "1.65",
     "Normal Pelli-Robson contrast sensitivity is about 1.65 log units or better."),
    ("optics", "What does the potential acuity meter estimate?",
     "The acuity the retina could achieve through a media opacity", "media opacity",
     "The potential acuity meter estimates retinal potential through media opacity."),
    ("optics", "How is Snellen acuity defined?",
     "The test distance over the distance at which the letter subtends 5 minutes of arc",
     "5 minutes",
     "Snellen acuity is test distance divided by the distance where the letter subtends 5 minutes."),
    ("optics", "What does a keratometer measure?",
     "Corneal curvature from the size of reflected mire images over about a 3 millimeter zone",
     "mire",
     "A keratometer infers corneal curvature from reflected mire image size."),
    ("optics", "What happens to sagittal depth when base curve steepens?",
     "It increases", "increases",
     "Sagittal depth increases as the base curve steepens."),
    ("optics", "What happens to sagittal depth when lens diameter increases?",
     "It increases", "increases",
     "Sagittal depth increases with larger lens diameter."),
    ("optics", "What is the near point of convergence on average?",
     "About 6 to 10 centimeters from the bridge of the nose", "6 to 10",
     "The average near point of convergence is 6 to 10 centimeters."),
    ("optics", "What does vergence amplitude measure?",
     "The total range of convergence and divergence in prism diopters", "vergence",
     "Vergence amplitude is the total convergence and divergence range."),
    ("optics", "What is normal positive fusional vergence at near roughly?",
     "Break near 24 prism diopters base out", "24",
     "Normal near positive fusional vergence breaks around 24 prism diopters base out."),
    ("optics", "What does Sheard's criterion require?",
     "Compensating fusional reserve of at least twice the heterophoria", "twice",
     "Sheard's criterion demands fusional reserves of at least twice the phoria."),
    ("optics", "What is fixational eye movement called when the eye drifts slowly?",
     "Drift, with microsaccades correcting it", "Drift",
     "Slow fixational drift is corrected by microsaccades."),
    ("optics", "What is the purpose of the duochrome test endpoint?",
     "Balance red and green clarity to avoid over-minusing", "over-minusing",
     "Duochrome balances red and green to avoid over-minusing."),
    ("optics", "What is the near point of accommodation?",
     "The closest point that stays in clear focus at maximum accommodation", "closest point",
     "The near point of accommodation is the closest clearly focused point."),
    ("optics", "What does Hofstetter's formula give for average amplitude of accommodation?",
     "18.5 minus 0.3 times age in years", "18.5",
     "Hofstetter's average amplitude formula is 18.5 minus 0.3 times age."),
]
