"""Optometry knowledge base, part 2: refraction procedures + ocular disease."""

KB2: list[tuple[str, str, str, str, str]] = [
    # ---------------- refraction / clinical procedures ----------------
    ("refraction", "What is the first step of a standard subjective refraction?",
     "Monocular best vision sphere after retinoscopy or autorefraction", "Monocular",
     "Subjective refraction starts with monocular best vision sphere."),
    ("refraction", "Why do you refract monocularly before binocular balancing?",
     "To find each eye's endpoint before fusion changes accommodation", "fusion",
     "Monocular refraction finds each endpoint before fusion alters accommodation."),
    ("refraction", "What is the maximum plus technique?",
     "Adding plus until vision blurs to give the clearest, least minus endpoint", "plus",
     "Maximum plus to maximum VA keeps the endpoint clearest with least minus."),
    ("refraction", "What does the phrase maximum plus maximum VA mean?",
     "The strongest plus power that still preserves best visual acuity", "strongest plus",
     "Maximum plus maximum VA is the strongest plus that keeps best acuity."),
    ("refraction", "Why must the phoropter be level with the pupil?",
     "Tilt induces unwanted cylinder and prismatic effects", "Tilt",
     "A level phoropter avoids induced cylinder and prism from tilt."),
    ("refraction", "What order do you refine astigmatism in subjective refraction?",
     "Axis first with the JCC, then cylinder power, then finalize sphere", "Axis",
     "Subjective astigmatism refinement runs axis, then power, then sphere."),
    ("refraction", "What is a binocular balance for?",
     "Equalizing accommodative state between the two eyes", "accommodative",
     "Binocular balance equalizes accommodation between both eyes."),
    ("refraction", "Which test dissociates the eyes vertically for balance?",
     "Vertical prism dissociated balance with a 3 to 4 prism diopter base up", "Vertical prism",
     "A 3 to 4 prism diopter vertical prism dissociates the eyes for balance."),
    ("refraction", "What is cycloplegia?",
     "Paralysis of the ciliary muscle with drops such as cyclopentolate", "cyclopentolate",
     "Cycloplegia paralyzes the ciliary muscle using drops like cyclopentolate."),
    ("refraction", "When is cycloplegic refraction most important?",
     "Children and hyperopes with strong accommodation", "Children",
     "Cycloplegic refraction matters most in children and hyperopes."),
    ("refraction", "What is myopia?",
     "A refractive error where light focuses in front of the retina, causing blur at distance",
     "in front of the retina",
     "Myopia focuses light in front of the retina and blurs distance vision."),
    ("refraction", "What is hyperopia?",
     "A refractive error where light focuses behind the retina", "behind",
     "Hyperopia focuses light behind the retina."),
    ("refraction", "What is astigmatism?",
     "A refractive error with different powers in different meridians from a non-spherical cornea or lens",
     "meridians",
     "Astigmatism gives different power in different meridians."),
    ("refraction", "What is presbyopia correction with progressive lenses called?",
     "A simultaneous vision lens with distance, intermediate, and near zones", "simultaneous",
     "Progressive lenses are simultaneous vision lenses with distance to near zones."),
    ("refraction", "What is the soft touch endpoint for duochrome after binocular balance?",
     "Red slightly clearer to keep the patient from over-minusing", "Red",
     "Leave duochrome slightly red to protect against over-minusing."),
    ("refraction", "What is retinoscopy used for?",
     "Objectively finding the refractive error from the reflex at the pupil", "reflex",
     "Retinoscopy measures refractive error from the pupillary light reflex."),
    ("refraction", "What does a scissored retinoscopic reflex suggest?",
     "Irregular astigmatism, such as keratoconus", "keratoconus",
     "A scissored reflex hints at irregular astigmatism like keratoconus."),
    ("refraction", "What does an dim reflex at the pupil edge suggest?",
     "A small pupil or media opacity reducing the reflex", "media opacity",
     "A dim peripheral reflex suggests small pupil or media opacity."),
    ("refraction", "How far should the trial frame vertex be from the cornea?",
     "About 12 to 14 millimeters", "12 to 14",
     "Trial frames sit about 12 to 14 millimeters from the cornea."),
    ("refraction", "What is a fogging endpoint sign in binocular balance?",
     "Both eyes equally blurred with plus so accommodation is relaxed", "equally blurred",
     "Equal plus blur in both eyes signals balanced relaxed accommodation."),
    ("refraction", "What is the Humphriss immediate contrast technique?",
     "A binocular fogging balance using plus lenses and duochrome", "binocular fogging",
     "Humphriss immediate contrast balances binocularly with fogging plus duochrome."),
    ("refraction", "What is anisometropia?",
     "A difference in refractive error between the two eyes", "difference",
     "Anisometropia is an interocular difference in refractive error."),
    ("refraction", "What is antimetropia?",
     "One eye myopic and the other hyperopic", "myopic",
     "Antimetropia is myopia in one eye and hyperopia in the other."),
    ("refraction", "What is a common aniseikonia workaround at near for anisometropia?",
     "Contact lenses because they reduce spectacle magnification differences", "Contact lenses",
     "Contact lenses reduce magnification mismatch in anisometropia."),
    ("refraction", "What does the phrase pulling plus mean?",
     "Reducing minus power until blur just appears to avoid overcorrection", "Reducing minus",
     "Pulling plus means removing minus until the first blur."),
    ("refraction", "What does a chromostereopsis check infer?",
     "Whether the patient is over-minused from red green focus differences", "over-minused",
     "Red focusing closer than green can flag over-minusing."),

    # ---------------- ocular disease ----------------
    ("disease", "What is the normal intraocular pressure range?",
     "10 to 21 millimeters of mercury", "10 to 21",
     "Normal intraocular pressure runs from 10 to 21 millimeters of mercury."),
    ("disease", "What is the most common primary open angle glaucoma risk factor besides IOP?",
     "Age and family history", "family history",
     "Age and family history are major glaucoma risk factors beyond IOP."),
    ("disease", "Which class is first line therapy for primary open angle glaucoma?",
     "Prostaglandin analogs such as latanoprost", "Prostaglandin",
     "Prostaglandin analogs like latanoprost are first line for open angle glaucoma."),
    ("disease", "What side effect does latanoprost commonly cause?",
     "Hyperemia, hypertrichosis, and iris darkening", "iris darkening",
     "Latanoprost can cause hyperemia, lash growth, and iris darkening."),
    ("disease", "Which angle finding defines primary angle closure glaucoma risk?",
     "A shallow anterior chamber angle on gonioscopy", "shallow",
     "Angle closure risk means a shallow angle seen on gonioscopy."),
    ("disease", "What is the definitive treatment for pupillary block angle closure?",
     "Laser peripheral iridotomy", "iridotomy",
     "Laser peripheral iridotomy relieves pupillary block."),
    ("disease", "What is normal tension glaucoma?",
     "Glaucomatous optic neuropathy with pressures within the normal range", "normal range",
     "Normal tension glaucoma damages the optic nerve despite normal IOP."),
    ("disease", "What ocular sign suggests glaucomatous optic nerve damage?",
     "Focal neuroretinal rim thinning and disc hemorrhage", "rim thinning",
     "Glaucoma shows focal rim thinning, notching, and disc hemorrhages."),
    ("disease", "Which test charts the visual field in glaucoma follow up?",
     "Standard automated perimetry, such as Humphrey 24-2 SITA", "perimetry",
     "Humphrey 24-2 SITA perimetry tracks glaucoma fields."),
    ("disease", "Which imaging test quantifies the retinal nerve fiber layer in glaucoma?",
     "Optical coherence tomography", "coherence",
     "OCT quantifies RNFL and ganglion cell loss in glaucoma."),
    ("disease", "What is a cataract?",
     "Any opacity of the crystalline lens", "opacity",
     "A cataract is an opacity of the crystalline lens."),
    ("disease", "Which cataract type is most linked to diabetes and steroids?",
     "Posterior subcapsular cataract", "Posterior subcapsular",
     "Posterior subcapsular cataracts link to diabetes and steroid use."),
    ("disease", "Which cataract type causes glare and myopic shift with age?",
     "Nuclear sclerotic cataract", "Nuclear",
     "Nuclear sclerotic cataracts cause glare and a myopic shift."),
    ("disease", "Which cataract type appears as wedge spokes on slit beam?",
     "Cortical cataract", "Cortical",
     "Cortical cataracts show wedge-like spokes."),
    ("disease", "What is the definitive treatment for visually significant cataract?",
     "Surgical extraction with intraocular lens implantation", "extraction",
     "Cataract surgery replaces the cloudy lens with an intraocular lens."),
    ("disease", "What are drusen in age related macular degeneration?",
     "Extracellular deposits beneath the retinal pigment epithelium", "deposits",
     "Drusen are extracellular deposits under the RPE in AMD."),
    ("disease", "Which vitamin formula reduces dry AMD progression?",
     "AREDS2 with lutein and zeaxanthin", "AREDS2",
     "The AREDS2 formula with lutein and zeaxanthin slows dry AMD."),
    ("disease", "What defines wet age related macular degeneration?",
     "Choroidal neovascularization with leakage or hemorrhage", "neovascularization",
     "Wet AMD means choroidal neovascularization leaks fluid or blood."),
    ("disease", "What is the standard treatment for wet AMD?",
     "Intravitreal anti-VEGF injections", "anti-VEGF",
     "Anti-VEGF intravitreal injections treat wet AMD."),
    ("disease", "Which bedside grid monitors metamorphopsia in AMD?",
     "The Amsler grid", "Amsler",
     "Patients self-check distortion with the Amsler grid."),
    ("disease", "What are the earliest retinal signs of diabetic retinopathy?",
     "Microaneurysms and dot-blot hemorrhages", "Microaneurysms",
     "Microaneurysms and dot-blot hemorrhages start diabetic retinopathy."),
    ("disease", "What retinal finding marks proliferative diabetic retinopathy?",
     "Neovascularization of the disc or retina", "Neovascularization",
     "Neovascularization defines proliferative diabetic retinopathy."),
    ("disease", "What is the laser treatment for proliferative diabetic retinopathy?",
     "Panretinal photocoagulation", "Panretinal",
     "Panretinal photocoagulation treats proliferative diabetic retinopathy."),
    ("disease", "How often should a diabetic patient have a dilated eye exam?",
     "At least once every year", "year",
     "Diabetic patients need a dilated exam at least yearly."),
    ("disease", "What is clinically significant diabetic macular edema treated with?",
     "Anti-VEGF injections or focal laser", "Anti-VEGF",
     "CSME is treated with anti-VEGF or focal laser."),
    ("disease", "Which retinal sign suggests hypertensive retinopathy?",
     "Arteriovenous nicking and cotton wool spots", "nicking",
     "AV nicking and cotton wool spots mark hypertensive retinopathy."),
    ("disease", "What is a cotton wool spot?",
     "A nerve fiber layer infarction from microvascular occlusion", "infarction",
     "A cotton wool spot is a nerve fiber layer infarct."),
    ("disease", "What are the symptoms of a retinal detachment?",
     "Flashes, floaters, and a curtain over the visual field", "curtain",
     "Retinal detachment causes flashes, floaters, and a curtain shade."),
    ("disease", "Which peripheral lesion predisposes to retinal detachment?",
     "Lattice degeneration", "Lattice",
     "Lattice degeneration predisposes to retinal tears."),
    ("disease", "What is the emergency presentation of central retinal artery occlusion?",
     "Sudden painless vision loss with a cherry red spot", "cherry red",
     "CRAO shows sudden painless loss with a cherry red spot."),
    ("disease", "What time window matters most in central retinal artery occlusion management?",
     "The first 90 to 240 minutes", "90 to 240",
     "CRAO salvage window is roughly the first 90 to 240 minutes."),
    ("disease", "What is the classic fundus sign of central retinal vein occlusion?",
     "Diffuse flame hemorrhages described as blood and thunder", "flame",
     "CRVO gives widespread flame hemorrhages, the blood and thunder fundus."),
    ("disease", "Which is the most common cause of red eye worldwide?",
     "Viral conjunctivitis", "Viral",
     "Viral conjunctivitis is the most common red eye cause."),
    ("disease", "Which sign suggests viral rather than bacterial conjunctivitis?",
     "Watery discharge with a preauricular lymph node", "preauricular",
     "Watery discharge plus a preauricular node suggests viral conjunctivitis."),
    ("disease", "Which finding suggests bacterial conjunctivitis?",
     "Purulent discharge with lids stuck shut in the morning", "Purulent",
     "Purulent discharge points to bacterial conjunctivitis."),
    ("disease", "What is the hallmark symptom of allergic conjunctivitis?",
     "Itching", "Itching",
     "Itching is the hallmark of allergic conjunctivitis."),
    ("disease", "Which conjunctival reaction suggests allergy?",
     "Papillae with a cobblestone appearance", "Papillae",
     "Cobblestone papillae indicate allergic reaction."),
    ("disease", "Which sign distinguishes limbal vernal keratoconjunctivitis?",
     "Horner-Trantas dots", "Trantas",
     "Horner-Trantas dots mark limbal vernal keratoconjunctivitis."),
    ("disease", "What is blepharitis?",
     "Chronic inflammation of the eyelid margins", "eyelid margins",
     "Blepharitis is chronic inflammation of the lid margins."),
    ("disease", "What is the mainstay of blepharitis therapy?",
     "Daily lid hygiene with warm compresses", "lid hygiene",
     "Warm compresses and lid hygiene anchor blepharitis care."),
    ("disease", "What is a hordeolum?",
     "An acute staphylococcal abscess of a gland in the eyelid", "abscess",
     "A hordeolum is an acute lid gland abscess."),
    ("disease", "What is a chalazion?",
     "A chronic sterile granuloma of a meibomian gland", "granuloma",
     "A chalazion is a chronic sterile meibomian granuloma."),
    ("disease", "Which sign is classic for herpetic dendritic keratitis?",
     "A branching dendritic corneal ulcer that stains with fluorescein", "dendritic",
     "HSV keratitis stains as a branching dendritic ulcer."),
    ("disease", "Why must steroids be avoided alone in dendritic keratitis?",
     "They worsen replicating herpes simplex epithelial infection", "worsen",
     "Steroids alone worsen epithelial herpes simplex keratitis."),
    ("disease", "What is keratoconus?",
     "A progressive thinning and cone-like ectasia of the cornea", "ectasia",
     "Keratoconus is progressive cone-like corneal ectasia."),
    ("disease", "Which corneal iron line is seen in keratoconus?",
     "The Fleischer ring", "Fleischer",
     "Keratoconus shows a Fleischer iron ring at the cone base."),
    ("disease", "Which vertical stromal stress lines appear in keratoconus?",
     "Vogt's striae", "Vogt",
     "Vogt's striae are vertical stress lines in keratoconus."),
    ("disease", "Which procedure slows keratoconus progression?",
     "Corneal collagen cross-linking", "cross-linking",
     "Collagen cross-linking halts keratoconus progression."),
    ("disease", "What sign is lid angle V shaped when looking down in keratoconus?",
     "Munson's sign", "Munson",
     "Munson's sign is the V shaped lower lid in downgaze."),
    ("disease", "What is a pterygium?",
     "A fibrovascular wing of conjunctiva growing onto the cornea", "wing",
     "A pterygium is a fibrovascular wing crossing onto the cornea."),
    ("disease", "What is a pinguecula?",
     "A yellowish elevated conjunctival deposit near the limbus", "yellowish",
     "A pinguecula is a yellowish limbal conjunctival deposit."),
    ("disease", "What is anterior uveitis?",
     "Inflammation of the iris and ciliary body", "iris",
     "Anterior uveitis inflames iris and ciliary body."),
    ("disease", "Which red eye pattern suggests anterior uveitis rather than conjunctivitis?",
     "Ciliary flush with photophobia and deep ache", "Ciliary flush",
     "Ciliary flush with photophobia suggests uveitis."),
    ("disease", "What cells does the slit lamp show in active anterior uveitis?",
     "White blood cells and flare in the anterior chamber", "flare",
     "Anterior chamber cells and flare mark active uveitis."),
    ("disease", "What is episcleritis?",
     "A benign sectoral inflammation of the episclera that blanches with phenylephrine",
     "phenylephrine",
     "Episcleritis is benign sectoral inflammation that blanches with phenylephrine."),
    ("disease", "Which red eye is painful and does NOT blanch with phenylephrine?",
     "Scleritis", "Scleritis",
     "Scleritis is painful deep inflammation that does not blanch."),
    ("disease", "Which systemic disease is scleritis associated with?",
     "Rheumatoid arthritis", "Rheumatoid",
     "Scleritis is often linked to rheumatoid arthritis."),
    ("disease", "What is a subconjunctival hemorrhage?",
     "A painless bleed between conjunctiva and sclera that resolves on its own", "painless",
     "Subconjunctival hemorrhage is painless and self limited."),
    ("disease", "What is dry eye disease also called?",
     "Keratoconjunctivitis sicca", "sicca",
     "Dry eye disease is keratoconjunctivitis sicca."),
    ("disease", "What does a tear break-up time below 10 seconds indicate?",
     "Tear film instability", "instability",
     "TBUT under 10 seconds signals tear film instability."),
    ("disease", "What Schirmer result indicates severe aqueous deficiency?",
     "Less than 5 millimeters of wetting in 5 minutes", "5",
     "Schirmer wetting under 5 millimeters means severe aqueous deficiency."),
    ("disease", "Which stain marks devitalized cells and mucin in dry eye?",
     "Lissamine green", "Lissamine",
     "Lissamine green stains devitalized cells and mucus."),
    ("disease", "Which vitamin deficiency causes night blindness and Bitot spots?",
     "Vitamin A", "Vitamin A",
     "Vitamin A deficiency causes night blindness and Bitot spots."),
    ("disease", "What is retinitis pigmentosa?",
     "An inherited rod-cone degeneration with night blindness and tunnel vision",
     "rod-cone",
     "Retinitis pigmentosa is an inherited rod-cone degeneration."),
    ("disease", "Which bone spicule pattern is classic in retinitis pigmentosa?",
     "Mid-peripheral bone spicule pigmentation", "bone spicule",
     "Bone spicule pigment clumps typify retinitis pigmentosa."),
    ("disease", "What is an ocular migraine aura?",
     "A spreading scintillating scotoma usually lasting under an hour", "scintillating",
     "Migraine aura is a spreading scintillating scotoma under an hour."),
    ("disease", "What visual symptom distinguishes transient monocular vision loss of giant cell arteritis?",
     "Amarosis fugax with jaw claudication and scalp tenderness in patients over 50",
     "jaw claudication",
     "GCA adds jaw claudication and scalp tenderness to transient vision loss."),
    ("disease", "Which lab test tracks giant cell arteritis inflammation?",
     "ESR and CRP", "ESR",
     "ESR and CRP track giant cell arteritis."),
    ("disease", "What is a stye in the external lid margin usually from?",
     "Staphylococcus aureus infection of a lash follicle", "Staphylococcus",
     "External styes usually come from staphylococcal follicle infection."),
    ("disease", "What is photokeratitis?",
     "A corneal sunburn from UV light, such as snow blindness", "UV",
     "Photokeratitis is UV corneal injury like snow blindness."),
    ("disease", "What is an arcus senilis?",
     "A gray lipid ring in the peripheral cornea", "lipid",
     "Arcus senilis is a peripheral corneal lipid ring."),
    ("disease", "When is corneal arcus in a young person concerning?",
     "It can signal dyslipidemia", "dyslipidemia",
     "Arcus in the young warrants a lipid workup."),
    ("disease", "What is a Kayser-Fleischer ring?",
     "A copper ring at Descemet's membrane in Wilson disease", "copper",
     "Kayser-Fleischer rings are copper deposits in Wilson disease."),
    ("disease", "What is a hypopyon?",
     "A white cell layer in the anterior chamber", "white cell",
     "A hypopyon is layered white cells in the anterior chamber."),
    ("disease", "What is a hyphema?",
     "Blood in the anterior chamber, often from trauma", "Blood",
     "A hyphema is blood layering in the anterior chamber."),
    ("disease", "Which drug class raises bleeding risk in traumatic hyphema?",
     "Aspirin and anticoagulants", "Aspirin",
     "Aspirin and anticoagulants worsen hyphema bleeding."),
    ("disease", "What is papilledema?",
     "Optic disc swelling from raised intracranial pressure", "intracranial",
     "Papilledema is disc swelling from raised intracranial pressure."),
    ("disease", "Which condition with obesity causes papilledema in young women?",
     "Idiopathic intracranial hypertension", "intracranial hypertension",
     "Idiopathic intracranial hypertension raises ICP and swells discs."),
    ("disease", "What is optic neuritis?",
     "Inflammatory demyelination of the optic nerve with pain on eye movement",
     "pain on eye movement",
     "Optic neuritis causes pain on eye movement and dyschromatopsia."),
    ("disease", "Which color sense fades early in optic neuritis?",
     "Red desaturation", "Red",
     "Red desaturation is an early optic neuritis sign."),
    ("disease", "What is Leber hereditary optic neuropathy?",
     "Mitochondrial DNA inherited rapid central vision loss in young men", "Mitochondrial",
     "LHON is mitochondrial, striking young men with central loss."),
    ("disease", "What is the leading cause of irreversible blindness worldwide?",
     "Cataract", "Cataract",
     "Cataract remains the leading cause of blindness worldwide."),
    ("disease", "What is the leading cause of irreversible blindness in developed countries among working adults?",
     "Glaucoma", "Glaucoma",
     "Glaucoma leads irreversible blindness in working-age adults."),
    ("disease", "Which infection classically causes chorioretinitis with head size and hearing signs in newborns?",
     "Congenital toxoplasmosis", "toxoplasmosis",
     "Congenital toxoplasmosis scars the retina with systemic signs."),
    ("disease", "What does a white pupillary reflex in an infant require ruling out first?",
     "Retinoblastoma", "Retinoblastoma",
     "Leukocoria in an infant must exclude retinoblastoma."),
    ("disease", "Which hereditary childhood cataract cause involves galactose metabolism?",
     "Galactosemia", "Galactosemia",
     "Galactosemia causes oil drop cataracts in infants."),
    ("disease", "What is thyroid eye disease also called?",
     "Graves orbitopathy", "Graves",
     "Thyroid eye disease is Graves orbitopathy."),
    ("disease", "Which extraocular muscle group enlarges first in thyroid eye disease?",
     "Inferior rectus and medial rectus", "Inferior rectus",
     "Graves orbitopathy thickens inferior and medial recti early."),
    ("disease", "What eyelid sign occurs in thyroid eye disease from sympathetic overactivity?",
     "Upper lid retraction with lid lag", "lid lag",
     "Sympathetic overactivity retracts lids and delays their descent."),
    ("disease", "Which medication for benign prostatic hyperplasia complicates cataract surgery?",
     "Tamsulosin", "Tamsulosin",
     "Tamsulosin causes intraoperative floppy iris syndrome."),
    ("disease", "Which TB drug causes optic neuropathy with red green color loss?",
     "Ethambutol", "Ethambutol",
     "Ethambutol can cause toxic optic neuropathy."),
    ("disease", "Which antimalarial requires baseline and serial visual field testing?",
     "Hydroxychloroquine", "Hydroxychloroquine",
     "Hydroxychloroquine needs baseline fields and OCT."),
    ("disease", "Which retinal toxicity pattern does hydroxychloroquine cause late?",
     "Bull's eye maculopathy", "Bull's eye",
     "Late hydroxychloroquine toxicity rings the fovea as bull's eye maculopathy."),
    ("disease", "Which seizure medication can cause acute myopia and angle closure?",
     "Topiramate", "Topiramate",
     "Topiramate can trigger acute myopia with angle closure."),
    ("disease", "Which acne medication causes dry eye and night vision complaints?",
     "Isotretinoin", "Isotretinoin",
     "Isotretinoin dries the eye and affects night vision."),
    ("disease", "Which chemotherapy alkylator causes hemorrhagic cystitis plus conjunctivitis at high dose?",
     "Cyclophosphamide", "Cyclophosphamide",
     "Cyclophosphamide can irritate ocular surfaces at high doses."),
    ("disease", "What is a chalasis of the conjunctiva called when it folds over the lid margin?",
     "Conjunctivochalasis", "Conjunctivochalasis",
     "Conjunctivochalasis is a redundant conjunctival fold."),
    ("disease", "What is the term for eyelid turning outward?",
     "Ectropion", "Ectropion",
     "Ectropion is an outward turning eyelid."),
    ("disease", "What is the term for eyelid turning inward with lash contact?",
     "Entropion", "Entropion",
     "Entropion turns the lid inward so lashes abrade the eye."),
    ("disease", "What is trichiasis?",
     "Misdirected lashes touching the eye", "Misdirected",
     "Trichiasis is misdirected lashes abrading the globe."),
    ("disease", "What is dermatochalasis?",
     "Redundant eyelid skin that may hang over the lid margin", "skin",
     "Dermatochalasis is redundant hanging lid skin."),
    ("disease", "What is ptosis?",
     "Drooping of the upper eyelid", "Drooping",
     "Ptosis is drooping of the upper lid."),
    ("disease", "Which myasthenia sign worsens through the day?",
     "Fatigable ptosis", "Fatigable",
     "Myasthenic ptosis fatigues as the day goes on."),
    ("disease", "What is anisocoria with light near dissociation in a young woman called?",
     "Adie tonic pupil", "Adie",
     "Adie tonic pupil shows light-near dissociation."),
    ("disease", "Which drop confirms Horner syndrome?",
     "Apraclonidion or cocaine; apraclonidine reverses anisocoria", "Apraclonidine",
     "Apraclonidine reversal confirms Horner syndrome."),
    ("disease", "What is the term for unequal pupil size?",
     "Anisocoria", "Anisocoria",
     "Anisocoria means unequal pupils."),
    ("disease", "What is nystagmus?",
     "Rhythmic involuntary oscillation of the eyes", "oscillation",
     "Nystagmus is rhythmic involuntary eye oscillation."),
    ("disease", "Which nystagmus direction suggests a vestibular or neurologic cause?",
     "Pure vertical or torsional", "vertical",
     "Vertical or torsional nystagmus suggests neurologic cause."),
]
